package com.example.birthformpdf.filler.ui

enum class AppLanguage { EN, MR }

data class Labels(
    val appTitle: String,
    val search: String,
    val records: String,
    val newRecord: String,
    val saveDraft: String,
    val generatePdf: String,
    val preview: String,
    val share: String,
    val print: String,
    val savePdf: String,
    val export: String,
    val edit: String,
    val delete: String,
    val duplicate: String,
    val childInfo: String,
    val motherInfo: String,
    val fatherInfo: String,
    val addressInfo: String,
    val informantInfo: String,
    val childName: String,
    val gender: String,
    val dateOfBirth: String,
    val timeOfBirth: String,
    val placeOfBirth: String,
    val birthType: String,
    val motherName: String,
    val aadhaarNumber: String,
    val age: String,
    val education: String,
    val occupation: String,
    val fatherName: String,
    val houseNumber: String,
    val street: String,
    val villageCity: String,
    val taluka: String,
    val district: String,
    val state: String,
    val pinCode: String,
    val informantName: String,
    val relation: String,
    val mobileNumber: String,
    val required: String,
    val saved: String,
    val pdfReady: String,
    val exportReady: String
)

fun labels(language: AppLanguage): Labels = when (language) {
    AppLanguage.EN -> Labels(
        appTitle = "Birth Form PDF Filler",
        search = "Search records",
        records = "Records",
        newRecord = "New",
        saveDraft = "Save Draft",
        generatePdf = "Generate PDF",
        preview = "Preview",
        share = "Share",
        print = "Print",
        savePdf = "Save PDF",
        export = "Export",
        edit = "Edit",
        delete = "Delete",
        duplicate = "Duplicate",
        childInfo = "Child Information",
        motherInfo = "Mother Information",
        fatherInfo = "Father Information",
        addressInfo = "Address Information",
        informantInfo = "Informant Information",
        childName = "Child Name",
        gender = "Gender",
        dateOfBirth = "Date of Birth",
        timeOfBirth = "Time of Birth",
        placeOfBirth = "Place of Birth",
        birthType = "Birth Type",
        motherName = "Mother Name",
        aadhaarNumber = "Aadhaar Number",
        age = "Age",
        education = "Education",
        occupation = "Occupation",
        fatherName = "Father Name",
        houseNumber = "House Number",
        street = "Street",
        villageCity = "Village/City",
        taluka = "Taluka",
        district = "District",
        state = "State",
        pinCode = "PIN Code",
        informantName = "Informant Name",
        relation = "Relation",
        mobileNumber = "Mobile Number",
        required = "Required",
        saved = "Draft saved",
        pdfReady = "PDF generated",
        exportReady = "Records exported"
    )
    AppLanguage.MR -> Labels(
        appTitle = "जन्म फॉर्म PDF फिलर",
        search = "नोंदी शोधा",
        records = "नोंदी",
        newRecord = "नवीन",
        saveDraft = "मसुदा जतन करा",
        generatePdf = "PDF तयार करा",
        preview = "पूर्वावलोकन",
        share = "शेअर",
        print = "प्रिंट",
        savePdf = "PDF जतन करा",
        export = "एक्सपोर्ट",
        edit = "संपादित करा",
        delete = "हटवा",
        duplicate = "प्रत तयार करा",
        childInfo = "बाळाची माहिती",
        motherInfo = "आईची माहिती",
        fatherInfo = "वडिलांची माहिती",
        addressInfo = "पत्त्याची माहिती",
        informantInfo = "माहिती देणाऱ्याची माहिती",
        childName = "बाळाचे नाव",
        gender = "लिंग",
        dateOfBirth = "जन्म दिनांक",
        timeOfBirth = "जन्म वेळ",
        placeOfBirth = "जन्म ठिकाण",
        birthType = "जन्म प्रकार",
        motherName = "आईचे नाव",
        aadhaarNumber = "आधार क्रमांक",
        age = "वय",
        education = "शिक्षण",
        occupation = "व्यवसाय",
        fatherName = "वडिलांचे नाव",
        houseNumber = "घर क्रमांक",
        street = "रस्ता",
        villageCity = "गाव/शहर",
        taluka = "तालुका",
        district = "जिल्हा",
        state = "राज्य",
        pinCode = "पिन कोड",
        informantName = "अर्जदाराचे नाव",
        relation = "नाते",
        mobileNumber = "मोबाईल क्रमांक",
        required = "आवश्यक",
        saved = "मसुदा जतन झाला",
        pdfReady = "PDF तयार झाली",
        exportReady = "नोंदी एक्सपोर्ट झाल्या"
    )
}
